applications:
    app:
        type: php:8.2

        build:
            flavor: symfony

        web:
            locations:
                "/":
                    root: public
                    passthru: /index.php
